version: "3.7"
services:
  backend:
    container_name: app_backend
    build: .
    restart: always
    ports:
      - 8080:8080
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend