version: "3.7"
services:
  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306